# Generated by Django 5.2.7 on 2025-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
